/* AUTO-GENERATED by scripts/generate-cms-content.mjs */
export type GeneratedPage = {
  id: string | number;
  slug: string;
  title?: string;
  status?: string;
  seo?: Record<string, any> | null;
  sections: Array<{ id?: string | number; sort?: number; type?: string; props?: Record<string, any> }>;
};

export const GENERATED_PAGES: GeneratedPage[] = [
  {
    "id": 1,
    "slug": "home",
    "title": "Home",
    "status": "published",
    "seo": null,
    "sections": [
      {
        "id": 1,
        "sort": 1,
        "type": "hero",
        "props": {
          "id": 1,
          "heading": "Building the Digital Roots of Future Agencies",
          "subheading": "Orchard Tech helps agencies scale with consulting, development, and automation.",
          "primary_cta_label": "Start Your Journey",
          "primary_cta_href": "/contact"
        }
      },
      {
        "id": 2,
        "sort": 20,
        "type": "feature_grid",
        "props": {
          "id": 1,
          "heading": "Comprehensive Solutions",
          "intro": null,
          "items": "[{\"title\":\"Tech Consulting\",\"description\":\"Roadmaps, architecture reviews, and pragmatic implementation guidance.\"},{\"title\":\"Custom Development\",\"description\":\"Web apps, integrations, and internal tools tailored to your workflows.\"},{\"title\":\"Workflow Automation\",\"description\":\"Reduce manual work with AI-assisted automations and clean handoffs.\"},{\"title\":\"Agency Support\",\"description\":\"Trusted technical partner support across retainers and project bursts.\"}]"
        }
      },
      {
        "id": 3,
        "sort": 30,
        "type": "rich_text",
        "props": {
          "id": 1,
          "content": "<h2>Technical Excellence, Minus the Jargon</h2><p>We focus on outcomes: faster delivery, fewer bottlenecks, and dependable systems that support your team and your clients.</p>",
          "max_width": "4xl"
        }
      },
      {
        "id": 4,
        "sort": 40,
        "type": "cta",
        "props": {
          "id": 1,
          "heading": "Ready to grow your technical capacity?",
          "body": "Tell us what you are building and where the bottlenecks are. We will help you map the fastest route to production.",
          "button_label": "Contact Orchard Tech",
          "button_href": "/contact"
        }
      }
    ]
  }
];
